name: Deploy client to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'kudos-client/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./kudos-client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0

    - name: Install dependencies
      run: npm install

    - name: Build the Vue app
      run: npm run build

    - name: Login to Firebase
      run: |
        npm install -g firebase-tools
        echo $FIREBASE_TOKEN | firebase login --no-interactive

    - name: Deploy to Firebase Hosting
      run: |
        firebase use --add $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
        firebase deploy --only hosting --token $FIREBASE_TOKEN

